#!/usr/bin/env bash
# Copyright (c) 2025 Jim - jim@jimscorner.co.uk
# /

export XAUTHORITY="$HOME"/.Xauthority
export DISPLAY=:0
export $(dbus-run-session)

if ! command -v calcurse >/dev/null ; then
	echo "calcurse must be installed for daily reminders to work!"
	exit 1
fi

items=$(calcurse -Qd1 | grep -v "[0-9]*/[0-9]*/[0-9]*:" | sed -e 's/-//g' -e 's/^[ \t]*//;s/[ \t]*$//')

notify-send -a "daily-reminder" "Daily reminder" "$items" -t 0
