#!/usr/bin/env bash

export PATH=$PATH:$HOME/.local/bin

WALLPAPER_DIR=$HOME/media/wallpapers/
WALLPAPER_IMG=$(sxiv -otb $WALLPAPER_DIR | head -n 1)

if [ "$WALLPAPER_IMG" = "" ]; then
	exit 1 
fi

if wal -n -i "$WALLPAPER_IMG" -o $HOME/.scripts/update-xresources ; then
	feh --bg-fill "$WALLPAPER_IMG"
else
	notify-send "Failed to set wallpaper" 
	exit 1
fi

if command -v pywalfox ; then
	pywalfox update
fi

if command -v pywal-discord ; then
	pywal-discord
fi
