#!/usr/bin/env bash

export PATH=$PATH:$HOME/.local/bin

WALLPAPER_DIR=$HOME/media/wallpapers/
WALLPAPER_IMG=$(sxiv -otb $WALLPAPER_DIR | head -n 1)

wal -n -l -i "$WALLPAPER_IMG" -o $HOME/.scripts/update-xresources
#cp $WALLPAPER_IMG ~/.cache/wal/wal
feh --bg-fill "$WALLPAPER_IMG"
