#!/usr/bin/env bash
# Copyright (c) 2025 Jim - jim@jimscorner.co.uk
# /

export PATH=$PATH:$HOME/.local/bin

WALLPAPER_DIR=$HOME/media/wallpapers/
WALLPAPER_IMG=$(sxiv -otbf $WALLPAPER_DIR | head -n 1)

if [ "$WALLPAPER_IMG" = "" ]; then
	exit 1 
fi

if wal -i "$WALLPAPER_IMG" -n -o $HOME/.scripts/update-xresources ; then
	feh --bg-fill --no-fehbg "$WALLPAPER_IMG"

	if command -v xdotool ; then
		xdotool key Super_L+Shift_L+q
	fi
else
	notify-send "Failed to set wallpaper" 
	exit 1
fi

if command -v pywalfox ; then
	pywalfox update
fi

if command -v pywal-discord ; then
	pywal-discord
fi
