#!/usr/bin/env bash
# Copyright (c) 2025 Jim - jim@jimscorner.co.uk
# /

file=$1
param=${2:-a}

c_template="#include \"$file.h\""

h_guard="$(echo $file | tr '[:lower:]' '[:upper:]' | sed 's|/|_|g')_H"
h_template="#ifndef $h_guard\n#define $h_guard\n\n#endif // $h_guard"

if [ "$file" = "" ]; then
	exit 0
fi

if [ $param != "-h" ]; then
	echo -e $c_template > src/$file.c
fi

if [ $param != "-c" ]; then
	echo -e $h_template > include/$file.h
fi
