#!/usr/bin/env bash

XRF=$HOME/.config/X11/xresources
DUNST=$HOME/.config/dunst/dunstrc

pywal_color() {
	sed "$1q;d" ~/.cache/wal/colors
}

xresource_set() {
	if ! grep -q $1 $XRF ; then
		echo "$1: $2" >> $XRF
	else 
		sed -i "s/$1\:.*/$1\: $(pywal_color $2)/" $XRF
	fi
}

xresource_set "Sxiv.background" 9
xresource_set "Sxiv.foreground" 8

xresource_set "dwm.normbgcolor" 1
xresource_set "dwm.normbordercolor" 14
xresource_set "dwm.normfgcolor" 8
xresource_set "dwm.selbgcolor" 2
xresource_set "dwm.selbordercolor" 8
xresource_set "dwm.selfgcolor" 8

xresource_set "st.color0" 1
xresource_set "st.color1" 2
xresource_set "st.color2" 3
xresource_set "st.color3" 4
xresource_set "st.color4" 5
xresource_set "st.color5" 6
xresource_set "st.color6" 7
xresource_set "st.color7" 8
xresource_set "st.color8" 9
xresource_set "st.color9" 10
xresource_set "st.color10" 11
xresource_set "st.color11" 12
xresource_set "st.color12" 13
xresource_set "st.color13" 14
xresource_set "st.color14" 15
xresource_set "st.color15" 16
xresource_set "st.background" 1
xresource_set "st.foreground" 8

sed -e "s|background = \".*\"|background = \"$(pywal_color 1)\"|g" \
	-e "s|foreground = \".*\"|foreground = \"$(pywal_color 8)\"|g" -i $DUNST
