#!/usr/bin/env bash

XRF=$HOME/.config/X11/xresources

pywal_color() {
	sed "$1!d" ~/.cache/wal/colors
}

sed -i "s/Sxiv.background\:.*/Sxiv.background\: $(pywal_color 8)/" $XRF
sed -i "s/Sxiv.foreground\:.*/Sxiv.foreground\: $(pywal_color 9)/" $XRF

sed -i "s/dwm.normbgcolor\:.*/dwm.normbgcolor\: $(pywal_color 8)/" $XRF
sed	-i "s/dwm.normbordercolor\:.*/dwm.normbordercolor\: $(pywal_color 1)/" $XRF
sed	-i "s/dwm.normfgcolor\:.*/dwm.normfgcolor\: $(pywal_color 9)/" $XRF
sed	-i "s/dwm.selbgcolor\:.*/dwm.selbgcolor\: $(pywal_color 8)/" $XRF
sed	-i "s/dwm.selbordercolor\:.*/dwm.selbordercolor\: $(pywal_color 2)/" $XRF
sed	-i "s/dwm.selfgcolor\:.*/dwm.selfgcolor\: $(pywal_color 7)/" $XRF

sed	-i "s/st.color0:.*/st.color0: $(pywal_color 1)/" $XRF
sed	-i "s/st.color1:.*/st.color1: $(pywal_color 2)/" $XRF
sed	-i "s/st.color2:.*/st.color2: $(pywal_color 3)/" $XRF
sed	-i "s/st.color3:.*/st.color3: $(pywal_color 4)/" $XRF
sed	-i "s/st.color4:.*/st.color4: $(pywal_color 5)/" $XRF
sed	-i "s/st.color5:.*/st.color5: $(pywal_color 6)/" $XRF
sed	-i "s/st.color6:.*/st.color6: $(pywal_color 7)/" $XRF
sed	-i "s/st.color7:.*/st.color7: $(pywal_color 8)/" $XRF
sed	-i "s/st.color8:.*/st.color8: $(pywal_color 9)/" $XRF
sed	-i "s/st.color9:.*/st.color9: $(pywal_color 10)/" $XRF
sed	-i "s/st.color10:.*/st.color10: $(pywal_color 11)/" $XRF
sed	-i "s/st.color11:.*/st.color11: $(pywal_color 12)/" $XRF
sed	-i "s/st.color12:.*/st.color12: $(pywal_color 13)/" $XRF
sed	-i "s/st.color13:.*/st.color13: $(pywal_color 14)/" $XRF
sed	-i "s/st.color14:.*/st.color14: $(pywal_color 15)/" $XRF
sed	-i "s/st.color15:.*/st.color15: $(pywal_color 16)/" $XRF
